# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6d67211213228400687b9c303cfef0c0a0e996a4b2fbddb1ef3ed49038c82fd2cbe37f230a484281d352b04f179bbf391be8d696e65d31c986ddafdae6f9ff

test:
  secret_key_base: 8c56c243f9630cbc235db5bb3baef756454157077b604679b6ff95f62ea93e993a15bdba5d8d74aff3a2b5e9815a7d6234e8e2fb3603ca8adc058993fbbd4b89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
